version: 2
executorType: docker
containerInfo:
  - image: trenpixster/elixir:1.4.0
stages:
  build:
    workDir: /home/circleci/project
    steps:
      - type: shell
        shell: /bin/sh
        pwd: /
        command: |
          ls -laR /
          netstat -plantu || ss -plntu
          ps auxfww
