version: 2
jobs:
  build:
    docker:
      - image: ruby:2.1.2
    working_directory: ~/project
    environment:
      _JAVA_OPTIONS: "-Xms128m -Xmx512m"
    steps:
      - run:
          command: |
            mkdir -p ~/.ssh
            ssh-keyscan -t rsa,dsa github.com >> ~/.ssh/known_hosts
            cat ~/.ssh/known_hosts
      - checkout
