version: 2

jobs:
  build:
    working_directory: /run/shm/tmp/
    docker:
      - image: ubuntu:14.04
      - image: mariadb:10.1
        environment:
          MYSQL_RANDOM_ROOT_PASSWORD: yes
          MYSQL_DATABASE: circle_test
          MYSQL_USER: ubuntu
          MYSQL_PASSWORD: ubuntu
    steps:
      - run: sleep 60 && curl 127.0.0.1:3306
