version: 2
executorType: docker
containerInfo:
  - image: maven
    env:
      - _JAVA_OPTIONS="-Xms512m -Xmx1024m"
      - GRADLE_OPTS='-Dorg.gradle.jvmargs="-Xmx2048m -XX:+HeapDumpOnOutOfMemoryError"'
stages:
  build:
    workDir: /project
    steps:
      - type: checkout
      - type: shell
        command: |
          df -h
          df -i
          free -m
          cat /proc/cpuinfo
      - type: shell
        command: |
          set -e
          mvn --help
          mvn -s settings.xml -U clean integration-test
