version: 2.0
jobs:
  build:
    machine:
      enabled: true
    steps:
      - type: checkout
      - echo "Hello There"
  test:
    steps:
      - run:
          name: Say Goodbye
          command: echo "Hello Goodbye"

workflows:
  version: 2
  btd:
    - build
    - test:
        requires:
          - build
