version: 2
executorType: docker
containerInfo:
  - image: node:alpine
stages:
  build:
    workDir: /
    steps:
      - type: shell
        shell: /bin/sh
        command: apt update && apt install -y git
      - type: checkout
      - type: shell
        shell: /bin/sh
        command: return 0
