version: 2
executorType: docker
containerInfo:
containerInfo:
  - image: lots0logs/circleci-wordpress
  - image: lots0logs/mariadb-alpine
    environment:
      MYSQL_ROOT_PASSWORD: password
  - image: lots0logs/nginx-fpm-alpine
  - image: node:alpine
  - image: ruby:alpine
stages:
  build:
    workDir: /opt
    steps:
      - type: shell
        command: return 0
