version: 2
executorType: docker
containerInfo:
  - image: node
stages:
  build:
    workDir: /
    steps:
      - type: shell
        command: |
          echo $TERM
          apt update && apt install -y sudo
          sudo echo $TERM
      - type: shell
        shell: /bin/sh
        command: echo $TERM
      - type: shell
        command: ./echo
