version: 2
executorType: docker
containerInfo:
  - image: wonderfall/nextcloud:11.0
    env:
      - ADMIN_USER=admin
      - ADMIN_PASSWORD=admin
stages:
  build:
    workDir: /
    steps:
      - type: shell
        command: |
          ls -ld /var/lib/nginx
          ls -laR /var/lib/nginx
          touch /var/lib/nginx/logs/error.log
          chmod 777 /var/lib/nginx/logs/error.log
          ls -la /var/lib/nginx/logs/
      - type: shell
        command: "run.sh"
