version: 2
jobs:
  build:
    docker:
      - image: php:7.1
    working_directory: /project
    steps:
      - run: 
          command: php -S 127.0.0.1:80
          background: true
      - run: sleep 30 && exit 0
