version: 2
executorType: docker
containerInfo:
  - image: node
stages:
  build:
    workDir: /
    steps:
      - type: checkout
      - type: shell
        command: apt update && apt install -y sudo
      - type: shell
        command: |
          echo $TERM
          sudo echo $TERM
      - type: shell
        shell: /bin/sh
        command: echo $TERM
      - type: shell
        command: chmod +x echo && ./echo

