version: 2
jobs:
  build:
    docker:
      - image: ubuntu:14.04
      - image: redis:2.8.19
    working_directory: /project
    steps:
      - run: |
          apt-get update && apt-get install -y redis-cli
          echo "CONFIG SET save ''" | redis-cli -x
