version: 2
executorType: machine

stages:
  build:
    workDir: ~/project
    steps:
      - type: checkout
      - type: shell
        command: sudo /bin/bash -c "sudo -u redis /usr/bin/redis-server /etc/redis/redis.conf"
        background: true
      - type: shell
        command: sudo ss -plntu
