version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.3.4-node-browsers
    resource_class: small
    steps:
      - run:
          shell: sudo bash -eo pipefail
          command: |
            free -m
            cat /proc/cpuinfo
