version: 2
jobs:
  build:
    docker:
      - image: docker:latest
    steps:
      - setup_remote_docker
      - run: docker run -d circleci/postgres:9.4-ram
      - run: sleep 30
      - run: docker ps -a
