version: 2
executorType: docker
containerInfo:
  - image: maven
    env:
      - MAVEN_OPTS="-Xms512m -Xmx1024m"
stages:
  build:
    workDir: /project
    steps:
      - type: checkout
      - type: shell
        command: |
          df -h
          df -i
          free -m
          cat /proc/cpuinfo
      - type: shell
        command: |
          set -e
          mvn --help
          #mvn -s settings.xml -U clean integration-test
