version: 2
executorType: docker
containerInfo:
  - image: node:alpine
stages:
  build:
    workDir: /home/circleci/project
    steps:
      - type: shell
        shell: /bin/sh
        pwd: /
        command: apk -U add git openssh
      - type: checkout
      - type: shell
        shell: /bin/sh
        command: return 0
