general:
  branches:
    ignore:
      - ignore

version: 2
executorType: docker
containerInfo:
  - image: node:alpine
  - image: ruby:alpine
stages:
  build:
    workDir: /home/ubuntu/project
    steps:
      - type: shell
        command: return 0
