version: 2
executorType: docker
containerInfo:
  - image: ruby:2.4.0-alpine
stages:
  build:
    workDir: /some-dir
    steps:
      - type: shell
        pwd: /
        name: Install Build Dependencies
        command: apk add --update openssh git make gcc libc-dev
