version: 2
executorType: machine

stages:
  build:
    workDir: ~/project
    steps:
      - type: checkout
      - type: shell
        command: sudo /bin/bash -c "updatedb && locate php"
        background: true
      - type: shell
        command: PATH="/usr/bin:$PATH" php --version
