version: 2

jobs:
  package_template: &package
    working_directory: ~/go/src/github.com/fuubar/endland/
    docker:
      - image: host.io/fuubar-docker-images/xenial-base:1.2
    steps:
      - checkout
      - run: git pull origin $CIRCLE_BRANCH --depth=1000000
      - run: ./external_docker_build.sh "$PACKAGE"

  reservoir:
    <<: *package
    environment:
      PACKAGE: "github.com/fuubar/endland/reservoir"


workflows:
  version: 2
  build:
    jobs:
      - reservoir
