version: 2
jobs:
  reservoir:
    <<:  *go_package_build
    environment:
      PACKAGE: github.com/path/reservoir

workflows:
  version: 2
  build:
    jobs:
      - reservoir

go_package_build_template: &go_package_build
  working_directory: /root/go/src/github.com/reservoir
  docker:
    - image: buildpack-deps:jessie
  steps:
    - exit 0
