version: 2
executorType: docker
containerInfo:
  - image: centos:7
stages:
  build:
    workDir: /
    steps:
      - type: shell
        name: Install Docker Engine
        command: |
          curl -L -o /tmp/docker.tgz https://get.docker.com/builds/Linux/x86_64/docker-1.12.3.tgz
          tar -xz -C /tmp -f /tmp/docker.tgz
          mv /tmp/docker/docker* /usr/bin/

          curl -L "https://github.com/docker/compose/releases/download/1.9.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/bin/docker-compose
          chmod +x /usr/bin/docker-compose

      - type: setup-docker-engine
      - type: shell
        name: "Verify Docker is functional"
        command: |
          docker --version
          docker-compose --version
          docker run -d -p 15672:15672 rabbitmq:3-management
          sleep 5 && curl -I -XGET 'localhost:15672'
