version: 2
executorType: machine

stages:
  build:
    workDir: ~/project
    steps:
      - type: checkout
      - type: shell
        command: sudo cat /etc/*release*
      - type: shell
        command: psql --version
