version: 2.0
jobs:
  test:
    machine: true
    working_directory: ~/project
    steps:
      - run:
          name: Say Goodbye
          command: echo "Hello Goodbye"

workflows:
  version: 2
  build:
    jobs:
      - test
