version: 2
executorType: machine

stages:
  build:
    workDir: ~/project
    environment:
      - PATH: "/opt/circleci/nodejs/v6.1.0/bin:/opt/google-cloud-sdk/bin:/opt/circleci/.rvm/gems/ruby-2.3.1/bin:/opt/circleci/.rvm/gems/ruby-2.3.1@global/bin:/opt/circleci/.rvm/rubies/ruby-2.3.1/bin:/home/circleci/.go_workspace/bin:/usr/local/go/bin:/opt/circleci/nodejs/v6.1.0/bin:/usr/local/apache-maven/bin:/home/circleci/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/gradle-1.10/bin:/opt/circleci/.rvm/bin:/opt/circleci/.rvm/bin"
    steps:
      - type: checkout
      - type: shell
        command: |
          sudo rm /usr/bin/python
          sudo ln -s /usr/bin/python3 /usr/bin/python
      - type: shell
        command: |
          python --version
          ls -la /usr/bin/pip*
      - type: shell
        command: |
          sudo -u root /bin/bash -c "apt update && apt search pip3 && apt install -y pip3*"
          pip3 install flake8
