version: 2
executorType: docker
containerInfo:
  - image: openjdk:8
stages:
  build:
    workdir: /project
    steps:
    - type: shell
      pwd: /
      command: |
        echo "test"
        curl -L -o /tmp/docker.tgz https://get.docker.com/builds/Linux/x86_64/docker-1.12.6.tgz
        tar -xz -C /tmp -f /tmp/docker.tgz
        mv /tmp/docker/docker* /usr/bin/
    - type: setup-docker-engine
    - type: shell
      pwd: /
      command: |
        docker run -it ubuntu:latest "apt update && apt install -y mtr && mtr -r google.com"
