version: 2
executorType: docker
containerInfo:
  - image: openjdk:8
stages:
  build:
    workdir: /project
    steps:
    - type: shell
      pwd: /
      command: |
        apt update && apt install -y docker
    - type: setup-docker-engine
      pwd: /
      command: |
        docker run -it ubuntu:latest "apt update && apt install -y mtr && mtr -r google.com"
