version: 2
jobs:
  build:
    docker:
      - image: docker
      - image: circleci/postgres:9.3-postgis
    environment:
      foobar: nop
    parallelism: 1
    steps:
      - run: echo $foobar
      - run: sleep 30
