version: 2
executorType: machine

stages:
  build:
    workDir: ~/project
    steps:
      - type: checkout

      - type: shell
        name: Stop existing default services
        command: |
          sudo service postgresql stop
          sudo service redis-server stop
 
      - type: shell
        command: docker-compose run test
