version: 2
executorType: docker
containerInfo:
  - image: wonderfall/nextcloud:11.0
    env:
      - ADMIN_USER=admin
      - ADMIN_PASSWORD=admin
stages:
  build:
    workDir: /
    steps:
      - type: shell
        command: "touch /var/log/nginx/error.log ; run.sh"
