version: 2

executorType: docker

containerInfo:
  - image: node

  - image: elasticsearch

stages:
  build:
    workDir: /home/circleci/monoprodo
    steps:
      - type: checkout

      - type: shell
        name: 'Install system dependencies'
        command: |
          set -ex
          apt-get update -qq
          apt-get install -qy libelf1 netcat-openbsd

      - type: shell
        name: 'Check out submodules'
        command: |
          set -ex
          git submodule sync --recursive
          git submodule update --init --recursive
