version: 2
executorType: docker
containerInfo:
  - image: node:alpine
  - image: ruby:alpine
  - image: elasticsearch:alpine
  - image: php:alpine
  - image: golang:alpine
stages:
  build:
    workDir: /
    steps:
      - type: shell
        command: return 0
