version: 2
executorType: docker
containerInfo:
containerInfo:
  - image: lots0logs/mariadb-alpine
  - image: lots0logs/nginx-fpm-alpine
stages:
  build:
    workDir: /opt
    steps:
      - type: shell
        command: return 0
