version: 2
jobs:
  build:
    docker:
      - image: buildpack-deps:jessie
    working_directory: ~/project
    steps:
      - checkout
      - run: echo 'export PATH="/thisisntreal:/usr/local/bin:$PATH"
      - run: echo $PATH
