version: 2
executorType: machine

stages:
  build:
    workDir: ~/project
    steps:
      - type: checkout
      - type: shell
        command: |
          echo $PATH
          export PATH="/usr/bin:/usr/local/bin:/bin:/usr/sbin:/sbin"
          which python
          which python3
          python --version
          python3 --version
          /usr/bin/python --version
          /usr/bin/python3 --version
          sudo rm /usr/bin/python
          sudo ln -s /usr/bin/python3 /usr/bin/python
          python --version
