version: 2
executorType: docker
containerInfo:
  - image: ubuntu:14.04
stages:
  delegate:
    workdir: /
    steps:
    - type: shell
      command: |
        echo "delegate"
  build:
    workdir: /
    steps:
    - type: shell
      command: |
        echo "build"
