version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.3.4
    steps:
      - run: 
          command: curl http://package.elm-lang.org/all-packages?elm-package-version=0.18
          shell: bash --login -eo pipefail
