version: 2
executorType: docker
containerInfo:
  - image: openjdk:8
stages:
  build:
    workdir: /project
    steps:
    - type: shell
      shell: /bin/sh
      pwd: /
      command: |
        mtr -r google.com
        sudo mtr -r google.com
