version: 2.0
jobs:
  build:
    machine: true
    working_directory: ~/project
    steps:
      - checkout
      - run: echo "Hello There"
  test:
    machine: true
    working_directory: ~/project
    steps:
      - run:
          name: Say Goodbye
          command: echo "Hello Goodbye"

workflows:
  version: 2.0
  btd:
    jobs:
      - build
      - test:
          requires:
            - build
