version: 2
executorType: docker
containerInfo:
  - image: mschewe/docker-mtr
stages:
  build:
    workdir: /project
    steps:
    - type: shell
      pwd: /
      command: |
        mtr -r google.com
