version: 2
executorType: docker
containerInfo:
  - image: mongo:2.6.8
stages:
  build:
    workDir: /home/circleci/project
    steps:
      - type: shell
        shell: /bin/sh
        pwd: /
        command: |
          ls -laR /data
          mongod
          mongod --smallfiles
