version: 2
executorType: machine
stages:
  build:
    workDir: /home/circleci/project
    steps:
      - type: checkout
      - type: shell
        shell: /bin/sh
        name: Stop Postgres
        command: sudo service postgresql stop ; sudo netstat -plntu
      - type: shell
        shell: /bin/sh
        name: Docker Debug
        command: |
          docker run -d --name postgres -p 5432:5432 -e POSTGRES_USER=ubuntu -e POSETGRES_DB=circle_ruby_test rohara/postgres:0.3
          sleep 35 
          curl 127.0.0.1:5432 
          sudo netstat -plntu
          docker logs postgres
