version: 2
executorType: machine

stages:
  build:
    workDir: ~/project
    steps:
      - type: checkout
      - type: shell
        command: |
          which python
          which python3
      - type: shell
        command: sudo ls -l /usr/local/bin/
      - type: shell
        command: sudo ls -l /usr/bin/
         
