version: 2
executorType: machine

stages:
  build:
    workDir: ~/project
    steps:
      - type: checkout
      - type: shell
        command: |
          export PATH="/usr/bin:$PATH"
          which python
          which python3
          python --version
          python3 --version
          /usr/bin/python --version
          /usr/bin/python3 --version
