version: 2
executorType: docker
containerInfo:
  - image: maven
stages:
  build:
    workDir: /project
    steps:
      - type: checkout
      - type: shell
        command: |
          set -e
          mvn --help
          mvn -s settings.xml -U clean integration-test
