aliases:
  - &basecontainer
    image: circleci/ruby:2.3.3
    environment:
      FOO_BAR: true
version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
      - *basecontainer
    steps:
      - run: echo $FOO_BAR
