version: 2
jobs:
  build:
    docker:
      - image: docker
    resource_class: xlarge
    environment:
      foobar: nop
    parallelism: 1
    steps:
      - run: echo $foobar
      - run: sleep 30
