version: 2
executorType: machine

stages:
  build:
    workDir: ~/project
    steps:
      - type: checkout
      - type: shell
        command: |
          set +e
          sudo /bin/bash -c "set +e ; \ 
          ls -l /etc/init*/redis* ; \
          /etc/init/redis-server.conf start ; \
          systemctl start redis-server ; \
          cat /etc/init/redis-server.conf ; \
          ss -plntu"
