version: 2
executorType: docker
containerInfo:
  - image: maven:3.3.9-jdk-8
    cmd: ["/bin/bash"]
    env:
      - MAVEN_OPTS="-Xms512m -Xmx1024m"
stages:
  build:
    workDir: /project
    steps:
      - type: checkout
      - type: shell
        command: |
          ls -la
