version: 2
executorType: docker
containerInfo:
  - image: node:alpine
stages:
  build:
    workDir: /home/ubuntu/project
    steps:
      - type: shell
        command: sleep 0 && [[ -n "$CODECOV_TOKEN" ]] && bash <(curl --silent https://codecov.io/bash) -X gcov -X fix
