version: 2
executorType: machine

stages:
  build:
    workDir: ~/project
    steps:
      - type: checkout
      - type: shell
        command: sudo /bin/bash -c "apt update && apt search redis && ls -l /etc/init*/redis*"
