version: 2
executorType: docker
containerInfo:
  - image: node:alpine
  - image: rohara/postgres:0.1
    env:
      - POSTGRES_USER=ubuntu
      - POSTGRES_DB=circle_ruby_test
  - image: postgres:9.5
    env:
      - POSTGRES_USER=ubuntu
      - POSTGRES_DB=circle_ruby_test
stages:
  build:
    workDir: /home/circleci/project
    steps:
      - type: shell
        shell: /bin/sh
        pwd: /
        command: apk -U add git openssh curl
      - type: checkout
      - type: shell
        shell: /bin/sh
        command: sleep 15 ; curl 127.0.0.1:5432
