version: 2
executorType: docker
containerInfo:
  - image: node:alpine
  - image: ruby:alpine
  - image: elasticsearch:alpine
  - image: php:alpine
  - image: lots0logs/circleci-wordpress
stages:
  build:
    workDir: /
    steps:
