version: 2
jobs:
  reservoir:
    <<:  *go_package_build
    environment:
      PACKAGE: github.com/fuubar/endland/reservoir

go_package_build_template: &go_package_build
  working_directory: /root/go/src/github.com/fuubar/endland/
  docker:
    - image: host.io/fuubar-docker-images/xenial-base:1.2
  steps:
    - checkout
    - run: git pull origin $CIRCLE_BRANCH --depth=1000000
    - run: ./external_docker_build.sh "$PACKAGE"

workflows:
  version: 2
  build:
    jobs:
      - reservoir
