version: 2
jobs:
  build:
    machine: true
    resource_class: large
    working_directory: ~/project
    steps:
      - run: sudo apt-get update
      - run: sudo bash -c "yes y | do-release-upgrade"
