version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.3.3
    working_directory: /home/circleci/project
    steps:
      - run: mkdir -p spec/one/two/{foo,bar,args,kwargs}
      - run: touch spec/one/two/{foo,bar,args,kwargs}/{foo,bar,args,kwargs}_spec.rb
      - run: echo $(circleci tests glob "spec/**/*_spec.rb")
      - run: echo $(circleci tests glob "spec/**/**_spec.rb")
