version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.3.3-node-browsers
    steps:
      - checkout
      - run: mkdir artifacts
      - run: ls -laR ~ > artifacts/foo
      - store_artifacts:
          path: artifacts
