version: 2
jobs:
  build:
    docker:
      - image: docker:1.13
    working_directory: /project
    steps:
      - setup_remote_docker
      - run: |
          echo $DOCKER_TLS_VERIFY
          echo $DOCKER_HOST
