version: 2
executorType: docker
containerInfo:
  - image: maven
    env:
      - MAVEN_OPTS="-Xms512m -Xmx1024m"
stages:
  build:
    workDir: /project
    steps:
      - type: shell
        pwd: /
        command: |
          ps auxfww
