version: 2.0
jobs:
  build:
    machine: true
    working_directory: ~/project
    steps:
      - checkout
      - run: echo "Hello There"
  test:
    machine: true
    working_directory: ~/project
    steps:
      - run:
          name: Say Goodbye
          command: echo "Hello Goodbye"

workflow:
  version: 2
  btd:
    - build
    - test:
        requires:
          - build
