version: 2
executorType: docker
containerInfo:
  - image: ubuntu:14.04
stages:
  build:
    parallel: 36
    workDir: /home/ubuntu/project
    steps:
      - type: shell
        command: free -m
      - type: shell
        command: cat /sys/fs/cgroup/memory/memory.stat
