version: 2
executorType: machine

stages:
  build:
    workDir: ~/project
    steps:
      - type: checkout
      - type: shell
        command: |
          set +e
          sudo /bin/bash -c "\
          ls -l /etc/init*/redis* && \
          service redis start && \
          /etc/init/redis-server start && \
          ss -plntu"
