version: 2
executorType: machine

stages:
  build:
    workDir: ~/project
    steps:
      - type: checkout
      - type: shell
        command: sudo /bin/bash -c "apt-get update && apt-cache search php7 && apt-get install php7-cli"
      - type: shell
        command: php --version
