version: 2
executorType: docker
containerInfo:
  - image: golang:1.7.5-alpine
  - image: postgres:9.5
    cmd: ["localedef","-i","sv_SE","-c","-f","UTF-8","-A","/usr/share/locale/locale.alias","sv_SE.UTF-8","&&","postgres"]
    env:
      - LANG="sv_SE.utf8"
stages:
  build:
    workdir: /
    steps:
    - type: shell
      shell: /bin/sh
      pwd: /
      command: |
        apk add --update wget postgres
        postgres -h 127.0.0.1 -p 5432
