version: 2
jobs:
  build:
    docker:
      - image: docker:1.13
    working_directory: /project
    steps:
      - setup_remote_docker
      - run: |
          set +e
          ls -la /var/run/docker.sock
          ss -plntu || netstat -plntu
      
