version: 2
executorType: machine
containerInfo:
  - image: rohara/postgres:0.1
    env:
      - POSTGRES_USER=ubuntu
      - POSTGRES_DB=circle_ruby_test
stages:
  build:
    workDir: /home/circleci/project
    steps:
      - type: checkout
      - type: shell
        shell: /bin/sh
        name: Stop Postgres
        command: sudo service postgres stop ; sudo netstat -plntu
      - type: shell
        shell: /bin/sh
        name: Docker
        command: docker run --name postgres -p 5432:5432 -e POSTGRES_USER=ubuntu -e POSETGRES_DB=circle_ruby_test rohara/postgres:0.1
        background: true
      - type: shell
        name: Debug
        command: sleep 35 ; curl 127.0.0.1:5432 ; sudo netstat -plntu ; docker logs postgres
