version: 2
executorType: docker
containerInfo:
  - image: lots0logs/circleci-wordpress
    environment:
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_HOST: mariadb
      PHPVER: 5.6.29
      WPCLI_URL: 'https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar'
      _REPO: Divi
      WWWCONF_DIR: /etc/apache2/sites-available
      BASE_URL: 'http://elegantthemesdev.com:8080'
  - image: lots0logs/mariadb-alpine
    environment:
      MYSQL_ROOT_PASSWORD: password
  - image: lots0logs/nginx-fpm-alpine
  - image: node:alpine
  - image: ruby:alpine
stages:
  build:
    workDir: /
    steps:
