version: 2
executorType: docker
containerInfo:
  - image: node:alpine
  - image: ruby:alpine
stages:
  build:
    workDir: /home/circleci/project
    steps:
      - type: shell
        command: |
          touch file
          setfacl -m u:root:r file
          return 0
