version: 2
executorType: machine

stages:
  build:
    workDir: ~/project
    steps:
      - type: checkout
      - type: shell
        command: psql -c "CREATE USER tester WITH PASSWORD 'test_password';GRANT ALL ON ALL TABLES IN SCHEMA public TO tester;"
