version: 2
jobs:
  build:
    docker:
      - image: 6river/rosbuild-armhf@sha256:29b16c2e37a3e175da44ae88aae5c6cea6bb7d96e3713dd406fa07a9defdb07c
    working_directory: /project
    steps:
      - run: exit 0
