version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7.13
    working_directory: ~/project
    steps:
      - run: wget https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-160.0.0-linux-x86_64.tar.gz && tar zxvf google-cloud-sdk-160.0.0-linux-x86_64.tar.gz && rm google-cloud-sdk-160.0.0-linux-x86_64.tar.gz && cd google-cloud-sdk/ && yes y | sudo ./install.sh
