version: 2
executorType: docker
containerInfo:
  - image: node
stages:
  build:
    workDir: /
    steps:
      - type: shell
        shell: /bin/sh
        command: |
          touch file && \
          setfacl -m u:root:r file
