version: 2
executorType: machine

stages:
  build:
    workDir: ~/project
    steps:
      - type: checkout
      - type: shell
        command: |
          which python
          which python3
          python --version
          /opt/circleci/.pyenv/shims/python3 --version
          rm /opt/circleci/.pyenv/shims/python
          cp /opt/circleci/.pyenv/shims/python3 /opt/circleci/.pyenv/shims/python
          /opt/circleci/.pyenv/shims/python --version
