version: 2

executorType: docker

containerInfo:
  - image: node

  - image: elasticsearch

stages:
  build:
    workDir: ~/monoprodo
    steps:
      - type: checkout

      - type: shell
        name: 'Install system dependencies'
        command: |
          set -ex
          apt-get update -qq
          apt-get install -qy libelf1 netcat-openbsd

      - type: shell
        name: 'Check out submodules'
        command: |
          set -ex
          git submodule sync --recursive
          git submodule update --init --recursive

      - type: cache-restore
        key: root-{{ checksum "package.json" }}

      - type: cache-restore
        key: libs-utils-{{ checksum "libs/utils/package.json" }}

      - type: shell
        name: 'Install dependencies'
        command: npm install -q
        environment:
          NPM_CONFIG_UNSAFE_PERM: true

      - type: cache-save
        key: root-{{ checksum "package.json" }}
        paths: ['node_modules']
      - type: cache-save
        key: libs-utils-{{ checksum "libs/utils/package.json" }}
        paths: ['libs/utils/node_modules']

      - type: shell
        name: 'Run tests'
        command: npm test
        environment:
          TERM: dumb
          ELASTICSEARCH_HOST: localhost
          ELASTICSEARCH_PORT: 9200
