version: 2
executorType: machine

stages:
  build:
    workDir: ~/project
    steps:
      - type: checkout
      - type: shell
        command: |
          which python
          which python3
          python --version
          python3 --version
          sudo apt remove -y python2.7
          sudo apt install -y python3
          python --version
          python3 --version
          ls -l /usr/bin/
          which python
          echo $PATH
