version: 2
executorType: docker
containerInfo:
  - image: docker/compose:1.9.0
stages:
  build:
    workDir: /project
    steps:
      - type: shell
        pwd: /
        command: apk add --upgrade git openssh
      - type: checkout
      - type: setup-docker-engine
      - type: shell
        command: touch .foodydirect.env

      - type: shell
        command: docker-compose run test bundle install

      - type: shell
        command: docker-compose run test

      - type: shell
        command: docker-compose run test bundle exec rspec
