version: 2
executorType: docker
containerInfo:
  - image: docker:latest
stages:
  build:
    workDir: /project
    steps:
      - type: setup-docker-engine
      - type: shell
        command: |
          set +e
          docker login hub.devshipgo.com -u anyuser -p anypwd
          docker --insecure-registry=hub.devshipgo.com login hub.devshipgo.com -u anyuser -p anypwd
