version: '2'
services:

  postgres-db:
    image: postgres:9.4.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:
    ports:
      - '5432:5432'
    volumes:
      - database:/var/lib/postgresql/data

  redis:
    image: redis:3.2.2
    command: --appendonly yes
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:3.6.2-management
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/data

  gems:
    image: busybox
    volumes:
      - gem_cache:/gems

  codebase:
    image: busybox
    volumes:
      - .:/foodydirect

  mailcatcher:
    build: .
    command: bundle exec mailcatcher -f --ip=0.0.0.0 --http-port 80
    volumes_from:
      - gems
      - codebase
    ports:
      - '80:80'
    env_file:
      - .foodydirect.env
    environment:
      - RAILS_ENV=development

  sneakers:
    build: .
    command: bundle exec rake sneakers:run
    links:
      - postgres-db
      - redis
      - rabbitmq
    volumes_from:
      - gems
      - codebase
    env_file:
      - .foodydirect.env
    environment:
      - RAILS_ENV=development

  web:
    build: .
    command: bundle exec puma
    links:
      - postgres-db
      - redis
      - rabbitmq
      - sneakers
      - mailcatcher
    volumes_from:
      - gems
      - codebase
    ports:
      - '3000:3000'
    depends_on:
      - nginx
    env_file:
      - .foodydirect.env
    environment:
      - RAILS_ENV=development
      - PORT=3000

  nginx:
    image: foodydirecthub/docker-nginx-ssl:latest
    ports:
      - '443:443'

  remote:
    build: .
    volumes:
      - ~/.ssh:/root/.ssh
      - ~/.netrc:/root/.netrc
    volumes_from:
      - gems
      - codebase
    env_file:
      - .foodydirect.env
    environment:
      - RAILS_ENV=development

  test:
    build: .
    command: bundle exec rake db:drop db:create db:schema:load db:migrate
    links:
      - postgres-db
      - redis
      - rabbitmq
      - puma-test
      - hub
      - firefox
    volumes_from:
      - gems
      - codebase
    env_file:
      - .foodydirect.env
    environment:
      - RAILS_ENV=test

  puma-test:
    build: .
    command: bundle exec puma
    links:
      - postgres-db
      - redis
      - rabbitmq
    volumes_from:
      - gems
      - codebase
    ports:
      - '4000:4000'
    env_file:
      - .foodydirect.env
    environment:
      - RAILS_ENV=test
      - PORT=4000

  hub:
    image: selenium/hub:2.53.0
    environment:
      VIRTUAL_HOST: selenium.hub.docker
      GRID_TIMEOUT: 1200000
    ports:
      - 4444:4444

  firefox:
    image: selenium/node-firefox:2.53.0
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
    expose:
      - "5555"

  chrome:
    image: selenium/node-chrome:2.53.0
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
    expose:
      - "5555"

volumes:
  database: {}
  redis_data: {}
  rabbitmq_data: {}
  gem_cache: {}


