version: '2'
services:
  test:
    image: ubuntu:14.04
    command: (printf "PING\r\n";) | nc localhost 6379
    links:
      - redis

  redis:
    image: redis:3.2.2
    command: --appendonly yes
    ports:
      - '6379:6379'
