version: '2'
services:
  test:
    build: .
    command: bundle exec rake db:drop db:create db:schema:load db:migrate
    links:
      - redis

  redis:
    image: redis:3.2.2
    command: --appendonly yes
    ports:
      - '6379:6379'
